name: "Temporary placeholder for release issue creation to be merged into the release action"
on:
  workflow_dispatch:
    inputs:
      project:
        description: Jib project to release
        required: true
        default: (build-plan | core | maven | gradle | extension-common | maven-extension | gradle-extension)
      release_version:
        description: new release version
        required: true
        default: (for example, 0.1.0)

jobs:
  createissue:
    name: "Creating tracking issue for release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse Project
        run: |
          PROJECT=$( case ${{ github.event.inputs.project }} in
            extension-common) echo jib-plugins-extension-common ;;
            maven-extension)  echo jib-maven-plugin-extension-api ;;
            gradle-extension) echo jib-gradle-plugin-extension-api ;;
            maven|gradle)     echo jib-${{ github.event.inputs.project }}-plugin ;;
            *)                echo jib-${{ github.event.inputs.project }} ;;
          esac )
          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV

      - uses: JasonEtco/create-an-issue@v2
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         RELEASE_NAME: v${{ github.event.inputs.release_version }}-${{ github.event.inputs.project }}
         CHANGELOG_URL: https://github.com/GoogleContainerTools/jib/${{ env.PROJECT }}/CHANGELOG.md
         README_URL: "https://github.com/loosebazooka/actions-issue-creation-test/README.md"
         RELEASE_DRAFT: "https://github.com/loosebazooka/actions-issue-creation-test/releases"
         RELEASE_PR: "www.amazon.com"
        with:
          filename: .github/RELEASE/release_checklist.md
